version: '2'
services:
  membersrvc:
    ports:
    - "7054:7054"
    command: membersrvc
    environment:
      - MEMBERSRVC_CA_LOGGING_SERVER=ERROR 
      - MEMBERSRVC_CA_LOGGING_CA=ERROR 
      - MEMBERSRVC_CA_LOGGING_ECA=ERROR 
      - MEMBERSRVC_CA_LOGGING_ECAP=ERROR 
      - MEMBERSRVC_CA_LOGGING_ECAA=ERROR 
      - MEMBERSRVC_CA_LOGGING_ACA=ERROR 
      - MEMBERSRVC_CA_LOGGING_ACAP=ERROR 
      - MEMBERSRVC_CA_LOGGING_TCA=ERROR 
      - MEMBERSRVC_CA_LOGGING_TCAP=ERROR 
      - MEMBERSRVC_CA_LOGGING_TCAA=ERROR 
      - MEMBERSRVC_CA_LOGGING_TLSCA=ERROR 
